# Generated by Django 6.1 on 2026-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=150)),
                ('about_text', models.TextField(blank=True, help_text="Main 'About Us' description")),
                ('staff_description', models.TextField(blank=True, help_text='General blurb about the team')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Shop Info',
                'verbose_name_plural': 'Shop Info',
            },
        ),
        migrations.CreateModel(
            name='ShopLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Main Store', max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('workdays_text', models.CharField(blank=True, help_text="e.g. 'Mon–Fri'", max_length=100)),
                ('working_hours_weekdays', models.CharField(blank=True, help_text="e.g. '09:00–18:00'", max_length=100)),
                ('working_hours_weekends', models.CharField(blank=True, help_text="e.g. '10:00–14:00' or 'Closed'", max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
